/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Beam
         * @description Classify the beam, solve its reactions, and return exact SFD/BMD data.
         *
         *     With ``?steps=true`` the response also carries the worked steps (LaTeX).
         *     ``?method=...`` selects the classical solution method for indeterminate beams.
         */
        post: operations["analyze_beam_api_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab/tension": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lab Tension
         * @description Replay a loading history on a fresh round tension specimen (steel material lab).
         *
         *     Stateless: the whole history is sent each time, so any state is reproducible. Strain is
         *     commanded and the preset's material law decides the stress. Engineering stress (MPa) is
         *     force over the original area; strain is engineering strain (fraction); tension positive.
         */
        post: operations["lab_tension_api_v1_lab_tension_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisOut */
        AnalysisOut: {
            /**
             * Available Methods
             * @description Available classical solution methods for indeterminate beams
             */
            available_methods?: string[];
            /** @description Extreme-fibre bending stress when material and section are supplied */
            bending_stress?: components["schemas"]["BendingStressOut"] | null;
            /** @description Recognized standard textbook case if applicable */
            canonical?: components["schemas"]["CanonicalOut"] | null;
            classification: components["schemas"]["ClassificationOut"];
            /** Critical Points */
            critical_points: components["schemas"]["CriticalPointOut"][];
            /** @description Physical Euler-Bernoulli result when material and section are supplied */
            deflection?: components["schemas"]["DeflectionOut"] | null;
            extremes: components["schemas"]["ExtremesOut"];
            /** Reactions */
            reactions: components["schemas"]["ReactionOut"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /**
             * Selected Method
             * @description Currently selected solution method for worked steps
             */
            selected_method?: string | null;
            /** @description Maximum transverse shear stress when material and section are supplied */
            shear_stress?: components["schemas"]["ShearStressOut"] | null;
            /**
             * Steps
             * @description Worked steps; only present when requested with ?steps=true
             */
            steps?: components["schemas"]["StepOut"][] | null;
            /** Warnings */
            warnings: string[];
            /** Zero Shear Points */
            zero_shear_points: number[];
        };
        /** BeamIn */
        BeamIn: {
            /**
             * Hinges
             * @description Positions of internal moment hinges in m from the left end
             */
            hinges?: number[];
            /**
             * Length
             * @description m
             */
            length: number;
            /** Loads */
            loads?: (components["schemas"]["PointLoadIn"] | components["schemas"]["PointMomentIn"] | components["schemas"]["DistributedLoadIn"])[];
            /** @description Constant linear-elastic material for physical analysis */
            material?: components["schemas"]["MaterialIn"] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Section
             * @description Constant cross-section over the complete beam
             */
            section?: (components["schemas"]["RectangularSectionIn"] | components["schemas"]["CircularSectionIn"] | components["schemas"]["ISectionIn"] | components["schemas"]["TSectionIn"]) | null;
            /**
             * Spans
             * @description Contiguous property spans covering [0, L]; alternative to uniform material/section
             */
            spans?: components["schemas"]["PropertySpanIn"][] | null;
            /** Supports */
            supports: components["schemas"]["SupportIn"][];
        };
        /** BendingStressOut */
        BendingStressOut: {
            max_compression: components["schemas"]["ExtremeOut"] | null;
            max_tension: components["schemas"]["ExtremeOut"] | null;
            /** Segments */
            segments: components["schemas"]["BendingStressSegmentOut"][];
            /** Yield Exceeded */
            yield_exceeded: boolean;
            yield_location: components["schemas"]["ExtremeOut"] | null;
            /** Yield Ratio */
            yield_ratio: number;
        };
        /** BendingStressSegmentOut */
        BendingStressSegmentOut: {
            /**
             * Sigma Bottom
             * @description Bottom fibre stress ascending coefficients in t = x - x_start (kN/m²)
             */
            sigma_bottom: number[];
            /**
             * Sigma Top
             * @description Top fibre stress ascending coefficients in t = x - x_start (kN/m²)
             */
            sigma_top: number[];
            /** X End */
            x_end: number;
            /** X Start */
            x_start: number;
        };
        /** CanonicalOut */
        CanonicalOut: {
            /** Case Id */
            case_id: string;
            /**
             * Derivation
             * @description Step-by-step first-principles derivation (LaTeX)
             */
            derivation: string[];
            /**
             * Location Text
             * @description Position of extreme (LaTeX / text)
             */
            location_text: string;
            /** Name */
            name: string;
            /**
             * Result Text
             * @description Evaluated result with units (LaTeX)
             */
            result_text: string;
            /**
             * Substituted Formula
             * @description Formula with substituted values (LaTeX)
             */
            substituted_formula: string;
            /**
             * Symbolic Formula
             * @description Textbook formula (LaTeX)
             */
            symbolic_formula: string;
            /**
             * Symbolic Reactions
             * @description Reactions formula (LaTeX)
             */
            symbolic_reactions: string;
        };
        /** CircularSectionIn */
        CircularSectionIn: {
            /**
             * Diameter
             * @description m
             */
            diameter: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "circle";
            /**
             * Wall Thickness
             * @description m; omit for solid
             */
            wall_thickness?: number | null;
        };
        /** ClassificationOut */
        ClassificationOut: {
            /** Axial Degree */
            axial_degree: number;
            /** Bending Degree */
            bending_degree: number;
            /** Degree */
            degree: number;
            /** Equations */
            equations: number;
            /** Reason */
            reason?: string | null;
            /** Restraints */
            restraints: number;
            /**
             * Status
             * @enum {string}
             */
            status: "unstable" | "determinate" | "indeterminate";
        };
        /** CriticalPointOut */
        CriticalPointOut: {
            /**
             * Axial Left
             * @default 0
             */
            axial_left: number;
            /**
             * Axial Right
             * @default 0
             */
            axial_right: number;
            /** Moment Left */
            moment_left: number;
            /** Moment Right */
            moment_right: number;
            /** Shear Left */
            shear_left: number;
            /** Shear Right */
            shear_right: number;
            /** X */
            x: number;
        };
        /** DeflectionOut */
        DeflectionOut: {
            max_absolute: components["schemas"]["ExtremeOut"];
            max_downward: components["schemas"]["ExtremeOut"] | null;
            max_upward: components["schemas"]["ExtremeOut"] | null;
            /** Segments */
            segments: components["schemas"]["DeflectionSegmentOut"][];
        };
        /** DeflectionSegmentOut */
        DeflectionSegmentOut: {
            /**
             * Deflection
             * @description Ascending coefficients in t = x - x_start; displacement in m, upward positive
             */
            deflection: number[];
            /**
             * Slope
             * @description Ascending coefficients in t = x - x_start; rotation in rad
             */
            slope: number[];
            /** X End */
            x_end: number;
            /** X Start */
            x_start: number;
        };
        /** DistributedLoadIn */
        DistributedLoadIn: {
            /** End */
            end: number;
            /** Id */
            id: string;
            /** Start */
            start: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "distributed";
            /**
             * W End
             * @description kN/m, upward positive
             */
            w_end: number;
            /**
             * W Start
             * @description kN/m, upward positive
             */
            w_start: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExtremeOut */
        ExtremeOut: {
            /** Value */
            value: number;
            /** X */
            x: number;
        };
        /** ExtremesOut */
        ExtremesOut: {
            max_compression?: components["schemas"]["ExtremeOut"] | null;
            max_hogging: components["schemas"]["ExtremeOut"] | null;
            max_negative_shear: components["schemas"]["ExtremeOut"] | null;
            max_positive_shear: components["schemas"]["ExtremeOut"] | null;
            max_sagging: components["schemas"]["ExtremeOut"] | null;
            max_tension?: components["schemas"]["ExtremeOut"] | null;
        };
        /** ISectionIn */
        ISectionIn: {
            /**
             * Flange Thickness
             * @description m
             */
            flange_thickness: number;
            /**
             * Flange Width
             * @description m
             */
            flange_width: number;
            /**
             * Height
             * @description m
             */
            height: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "i";
            /**
             * Web Thickness
             * @description m
             */
            web_thickness: number;
        };
        /** LandmarkOut */
        LandmarkOut: {
            /**
             * Id
             * @description A proportional limit … F fracture
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Reached
             * @description The specimen has reached or passed this strain
             */
            reached: boolean;
            /** Strain */
            strain: number;
            /** Stress Mpa */
            stress_mpa: number;
        };
        /** MaterialIn */
        MaterialIn: {
            /**
             * Yield Strength Mpa
             * @description Yield strength in MPa
             */
            yield_strength_mpa: number;
            /**
             * Young Modulus Gpa
             * @description Young's modulus in GPa
             */
            young_modulus_gpa: number;
        };
        /** ModelOut */
        ModelOut: {
            /**
             * Kind
             * @constant
             */
            kind: "idealisation";
            /** Name */
            name: string;
            /**
             * Parameters
             * @description The preset's numeric parameters (stresses in MPa, strains as fractions)
             */
            parameters: {
                [key: string]: number;
            };
            /** Preset */
            preset: string;
            /** Young Modulus Gpa */
            young_modulus_gpa: number;
        };
        /** PointLoadIn */
        PointLoadIn: {
            /**
             * Fx
             * @description kN, rightward positive (horizontal)
             * @default 0
             */
            fx: number;
            /** Id */
            id: string;
            /**
             * Magnitude
             * @description kN, upward positive
             */
            magnitude: number;
            /** Position */
            position: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "point";
        };
        /** PointMomentIn */
        PointMomentIn: {
            /** Id */
            id: string;
            /**
             * Magnitude
             * @description kN·m, anticlockwise positive
             */
            magnitude: number;
            /** Position */
            position: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "moment";
        };
        /** ProofOut */
        ProofOut: {
            /**
             * Offset Strain
             * @description The offset (fraction): 0.002 is the usual 0.2 %
             */
            offset_strain: number;
            /**
             * Strain
             * @description Total strain where the offset line meets the curve
             */
            strain: number;
            /**
             * Stress Mpa
             * @description The offset proof strength, MPa
             */
            stress_mpa: number;
        };
        /** PropertySpanIn */
        PropertySpanIn: {
            material: components["schemas"]["MaterialIn"];
            /** Section */
            section: components["schemas"]["RectangularSectionIn"] | components["schemas"]["CircularSectionIn"] | components["schemas"]["ISectionIn"] | components["schemas"]["TSectionIn"];
            /**
             * X End
             * @description m from the left end
             */
            x_end: number;
            /**
             * X Start
             * @description m from the left end
             */
            x_start: number;
        };
        /** ReactionOut */
        ReactionOut: {
            /** Fx */
            fx: number;
            /** Fy */
            fy: number;
            /** Moment */
            moment: number;
            /** Support Id */
            support_id: string;
        };
        /** RectangularSectionIn */
        RectangularSectionIn: {
            /**
             * Height
             * @description m
             */
            height: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rectangle";
            /**
             * Wall Thickness
             * @description m; omit for solid
             */
            wall_thickness?: number | null;
            /**
             * Width
             * @description m
             */
            width: number;
        };
        /** ResetOpIn */
        ResetOpIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "reset";
        };
        /** SegmentOut */
        SegmentOut: {
            /**
             * Axial
             * @description Ascending coefficients of N(x) in t = x - x_start (kN, tension positive)
             */
            axial?: number[];
            /**
             * Moment
             * @description Ascending coefficients in t = x - x_start; valid strictly inside
             */
            moment: number[];
            /**
             * Shear
             * @description Ascending coefficients in t = x - x_start; valid strictly inside
             */
            shear: number[];
            /** X End */
            x_end: number;
            /** X Start */
            x_start: number;
        };
        /** ShearStressOut */
        ShearStressOut: {
            max_shear_stress: components["schemas"]["ExtremeOut"] | null;
        };
        /** SpecimenIn */
        SpecimenIn: {
            /**
             * Diameter Mm
             * @description mm, original diameter d0
             */
            diameter_mm: number;
            /**
             * Gauge Length Mm
             * @description mm, original gauge length L0
             */
            gauge_length_mm: number;
        };
        /** SpecimenOut */
        SpecimenOut: {
            /**
             * Area Mm2
             * @description Original area A0, mm²
             */
            area_mm2: number;
            /** Diameter Mm */
            diameter_mm: number;
            /** Gauge Length Mm */
            gauge_length_mm: number;
        };
        /** StepOut */
        StepOut: {
            /** At */
            at?: number | null;
            /**
             * Group
             * @enum {string}
             */
            group: "reactions" | "diagrams" | "extremes" | "physical";
            /**
             * Kind
             * @enum {string}
             */
            kind: "supports" | "loads" | "resultant" | "force_balance" | "moment_balance" | "reactions" | "axial" | "shear" | "moment" | "zero_shear" | "moment_at" | "extreme" | "slope" | "deflection" | "notice" | "bending_stress" | "shear_stress" | "yield_check";
            /**
             * Notes
             * @description Plain-text lines
             */
            notes?: string[];
            /**
             * Result
             * @description LaTeX
             */
            result?: string | null;
            /**
             * Substituted
             * @description LaTeX
             */
            substituted?: string | null;
            /**
             * Symbolic
             * @description LaTeX
             */
            symbolic?: string | null;
            /** Title */
            title: string;
            /** X End */
            x_end?: number | null;
            /** X Start */
            x_start?: number | null;
        };
        /** StrainOpIn */
        StrainOpIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "strain";
            /**
             * To
             * @description Total engineering strain to move to (fraction). Lower than now unloads.
             */
            to: number;
        };
        /** SupportIn */
        SupportIn: {
            /** Id */
            id: string;
            /**
             * Position
             * @description m from the left end
             */
            position: number;
            /**
             * Settlement
             * @description m, downward positive
             */
            settlement?: number | null;
            /**
             * Spring Ktheta
             * @description kN·m/rad, rotational spring stiffness
             */
            spring_ktheta?: number | null;
            /**
             * Spring Ky
             * @description kN/m, vertical spring stiffness
             */
            spring_ky?: number | null;
            /**
             * Type
             * @enum {string}
             */
            type: "pin" | "roller" | "fixed";
        };
        /** TSectionIn */
        TSectionIn: {
            /**
             * Flange Thickness
             * @description m
             */
            flange_thickness: number;
            /**
             * Flange Width
             * @description m
             */
            flange_width: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "t";
            /**
             * Web Depth
             * @description m
             */
            web_depth: number;
            /**
             * Web Thickness
             * @description m
             */
            web_thickness: number;
        };
        /** TensionIn */
        TensionIn: {
            /**
             * History
             * @description Loading history, replayed on a fresh specimen. Empty is a fresh specimen.
             */
            history?: (components["schemas"]["StrainOpIn"] | components["schemas"]["UnloadOpIn"] | components["schemas"]["ResetOpIn"])[];
            /**
             * Preset
             * @description Material preset id
             */
            preset: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            specimen: components["schemas"]["SpecimenIn"];
        };
        /** TensionOut */
        TensionOut: {
            /**
             * Landmarks
             * @description All six points A to F
             */
            landmarks: components["schemas"]["LandmarkOut"][];
            model: components["schemas"]["ModelOut"];
            /** @description 0.2 % offset proof point of the preset curve. Unloading from it leaves exactly the offset as permanent strain. */
            proof: components["schemas"]["ProofOut"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            specimen: components["schemas"]["SpecimenOut"];
            state: components["schemas"]["TensionStateOut"];
            /**
             * Trace
             * @description The stress-strain path taken, in order: dense on curved pieces, exact corners
             */
            trace: components["schemas"]["TracePointOut"][];
            /** Warnings */
            warnings?: string[];
        };
        /** TensionStateOut */
        TensionStateOut: {
            /**
             * Elastic Strain
             * @description strain minus plastic_strain; 0 after fracture (the recoverable part is lost)
             */
            elastic_strain: number;
            /**
             * Extension Mm
             * @description Extension of the gauge length, mm (strain times L0)
             */
            extension_mm: number;
            /**
             * Force Kn
             * @description Force, kN
             */
            force_kn: number;
            /**
             * Landmark
             * @description A to F when the strain equals that point exactly, otherwise null
             */
            landmark: string | null;
            /**
             * Max Strain
             * @description Largest strain reached on the loading curve
             */
            max_strain: number;
            /**
             * Plastic Strain
             * @description Permanent strain left if unloaded now (fraction)
             */
            plastic_strain: number;
            /**
             * Region
             * @enum {string}
             */
            region: "elastic" | "elastic_curving" | "yield_onset" | "yield_drop" | "yield_plateau" | "strain_hardening" | "necking" | "unloading" | "reloading" | "fractured";
            /**
             * Strain
             * @description Total engineering strain (fraction)
             */
            strain: number;
            /**
             * Stress Mpa
             * @description Engineering stress F/A0, MPa (never negative)
             */
            stress_mpa: number;
        };
        /** TracePointOut */
        TracePointOut: {
            /**
             * Plastic Strain
             * @description Permanent strain at this point (fraction)
             */
            plastic_strain: number;
            /**
             * Region
             * @enum {string}
             */
            region: "elastic" | "elastic_curving" | "yield_onset" | "yield_drop" | "yield_plateau" | "strain_hardening" | "necking" | "unloading" | "reloading" | "fractured";
            /** Strain */
            strain: number;
            /** Stress Mpa */
            stress_mpa: number;
        };
        /** UnloadOpIn */
        UnloadOpIn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "unload_to_zero_stress";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_beam_api_v1_analyze_post: {
        parameters: {
            query?: {
                steps?: boolean;
                method?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeamIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    lab_tension_api_v1_lab_tension_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TensionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TensionOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
