/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Beam
         * @description Classify the beam, solve its reactions, and return exact SFD/BMD data.
         *
         *     With ``?steps=true`` the response also carries the worked steps (LaTeX).
         */
        post: operations["analyze_beam_api_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisOut */
        AnalysisOut: {
            /** @description Recognized standard textbook case if applicable */
            canonical?: components["schemas"]["CanonicalOut"] | null;
            classification: components["schemas"]["ClassificationOut"];
            /** Critical Points */
            critical_points: components["schemas"]["CriticalPointOut"][];
            extremes: components["schemas"]["ExtremesOut"];
            /** Reactions */
            reactions: components["schemas"]["ReactionOut"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /**
             * Steps
             * @description Worked steps; only present when requested with ?steps=true
             */
            steps?: components["schemas"]["StepOut"][] | null;
            /** Warnings */
            warnings: string[];
            /** Zero Shear Points */
            zero_shear_points: number[];
        };
        /** BeamIn */
        BeamIn: {
            /**
             * Hinges
             * @description Positions of internal moment hinges in m from the left end
             */
            hinges?: number[];
            /**
             * Length
             * @description m
             */
            length: number;
            /** Loads */
            loads?: (components["schemas"]["PointLoadIn"] | components["schemas"]["PointMomentIn"] | components["schemas"]["DistributedLoadIn"])[];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Supports */
            supports: components["schemas"]["SupportIn"][];
        };
        /** CanonicalOut */
        CanonicalOut: {
            /** Case Id */
            case_id: string;
            /**
             * Derivation
             * @description Step-by-step first-principles derivation (LaTeX)
             */
            derivation: string[];
            /**
             * Location Text
             * @description Position of extreme (LaTeX / text)
             */
            location_text: string;
            /** Name */
            name: string;
            /**
             * Result Text
             * @description Evaluated result with units (LaTeX)
             */
            result_text: string;
            /**
             * Substituted Formula
             * @description Formula with substituted values (LaTeX)
             */
            substituted_formula: string;
            /**
             * Symbolic Formula
             * @description Textbook formula (LaTeX)
             */
            symbolic_formula: string;
            /**
             * Symbolic Reactions
             * @description Reactions formula (LaTeX)
             */
            symbolic_reactions: string;
        };
        /** ClassificationOut */
        ClassificationOut: {
            /** Axial Degree */
            axial_degree: number;
            /** Bending Degree */
            bending_degree: number;
            /** Degree */
            degree: number;
            /** Equations */
            equations: number;
            /** Reason */
            reason?: string | null;
            /** Restraints */
            restraints: number;
            /**
             * Status
             * @enum {string}
             */
            status: "unstable" | "determinate" | "indeterminate";
        };
        /** CriticalPointOut */
        CriticalPointOut: {
            /**
             * Axial Left
             * @default 0
             */
            axial_left: number;
            /**
             * Axial Right
             * @default 0
             */
            axial_right: number;
            /** Moment Left */
            moment_left: number;
            /** Moment Right */
            moment_right: number;
            /** Shear Left */
            shear_left: number;
            /** Shear Right */
            shear_right: number;
            /** X */
            x: number;
        };
        /** DistributedLoadIn */
        DistributedLoadIn: {
            /** End */
            end: number;
            /** Id */
            id: string;
            /** Start */
            start: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "distributed";
            /**
             * W End
             * @description kN/m, upward positive
             */
            w_end: number;
            /**
             * W Start
             * @description kN/m, upward positive
             */
            w_start: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExtremeOut */
        ExtremeOut: {
            /** Value */
            value: number;
            /** X */
            x: number;
        };
        /** ExtremesOut */
        ExtremesOut: {
            max_compression?: components["schemas"]["ExtremeOut"] | null;
            max_hogging: components["schemas"]["ExtremeOut"] | null;
            max_negative_shear: components["schemas"]["ExtremeOut"] | null;
            max_positive_shear: components["schemas"]["ExtremeOut"] | null;
            max_sagging: components["schemas"]["ExtremeOut"] | null;
            max_tension?: components["schemas"]["ExtremeOut"] | null;
        };
        /** PointLoadIn */
        PointLoadIn: {
            /**
             * Fx
             * @description kN, rightward positive (horizontal)
             * @default 0
             */
            fx: number;
            /** Id */
            id: string;
            /**
             * Magnitude
             * @description kN, upward positive
             */
            magnitude: number;
            /** Position */
            position: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "point";
        };
        /** PointMomentIn */
        PointMomentIn: {
            /** Id */
            id: string;
            /**
             * Magnitude
             * @description kN·m, anticlockwise positive
             */
            magnitude: number;
            /** Position */
            position: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "moment";
        };
        /** ReactionOut */
        ReactionOut: {
            /** Fx */
            fx: number;
            /** Fy */
            fy: number;
            /** Moment */
            moment: number;
            /** Support Id */
            support_id: string;
        };
        /** SegmentOut */
        SegmentOut: {
            /**
             * Axial
             * @description Ascending coefficients of N(x) in t = x - x_start (kN, tension positive)
             */
            axial?: number[];
            /**
             * Moment
             * @description Ascending coefficients in t = x - x_start; valid strictly inside
             */
            moment: number[];
            /**
             * Shear
             * @description Ascending coefficients in t = x - x_start; valid strictly inside
             */
            shear: number[];
            /** X End */
            x_end: number;
            /** X Start */
            x_start: number;
        };
        /** StepOut */
        StepOut: {
            /** At */
            at?: number | null;
            /**
             * Group
             * @enum {string}
             */
            group: "reactions" | "diagrams" | "extremes";
            /**
             * Kind
             * @enum {string}
             */
            kind: "supports" | "loads" | "resultant" | "force_balance" | "moment_balance" | "reactions" | "axial" | "shear" | "moment" | "zero_shear" | "moment_at" | "extreme" | "notice";
            /**
             * Notes
             * @description Plain-text lines
             */
            notes?: string[];
            /**
             * Result
             * @description LaTeX
             */
            result?: string | null;
            /**
             * Substituted
             * @description LaTeX
             */
            substituted?: string | null;
            /**
             * Symbolic
             * @description LaTeX
             */
            symbolic?: string | null;
            /** Title */
            title: string;
            /** X End */
            x_end?: number | null;
            /** X Start */
            x_start?: number | null;
        };
        /** SupportIn */
        SupportIn: {
            /** Id */
            id: string;
            /**
             * Position
             * @description m from the left end
             */
            position: number;
            /**
             * Type
             * @enum {string}
             */
            type: "pin" | "roller" | "fixed";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_beam_api_v1_analyze_post: {
        parameters: {
            query?: {
                steps?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeamIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
